# Generated by Django 4.1.2 on 2022-10-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="user",),
        migrations.DeleteModel(name="Friend",),
        migrations.DeleteModel(name="Post",),
    ]
