# Generated by Django 4.1.2 on 2022-11-22 11:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("weather", "0002_remove_post_user_delete_friend_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/media/images"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
