# Generated by Django 4.1.2 on 2022-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityimage", name="image", field=models.ImageField(upload_to=""),
        ),
    ]
