# Generated by Django 4.1.2 on 2022-11-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0005_rename_cityimage_city"),
    ]

    operations = [
        migrations.RenameModel(old_name="City", new_name="Cities",),
    ]
